name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: cmake configure
      run: cmake .
    - name: cmake build
      run: cmake --build .
      
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/pubsub
        path: pubsub
    - uses: actions/checkout@v1
      with:
        path: rucksack
    - name: copy cmake
      run: cp rucksack/WorkspaceCMakeList.txt CMakeLists.txt
    - name: cmake configure
      run: cmake .
    - name: cmake build
      run: cmake --build .
