name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/pubsub
        path: pubsub
    - uses: actions/checkout@v2
      with:
        path: rucksack
    - run: ls
    - run: ls pubsub
    - run: ls rucksack
    - name: copy cmake
      run: cp rucksack/WorkspaceCMakeLists.txt CMakeLists.txt
    - name: cmake configure
      run: cmake .
    - name: cmake build
      run: cmake --build .
      
  linux-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        repository: matt-attack/pubsub
        path: pubsub
    - uses: actions/checkout@v2
      with:
        path: rucksack
    - run: ls
    - run: ls pubsub
    - run: ls rucksack
    - name: build pubsub
      run: |
        cd pubsub
        cmake .
        cmake --build .
    - name: build rucksack
      run: |
        cd rucksack
        cmake .
        cmake --build .
